function chooseDate(date){const ar=selectedArchive(date);if(ar){openArchive(date);return}state.date=date;state.editorClosed=false;calendarDate=new Date(date+'T12:00:00');saveLocal();render();toast(fmt(date)+' tanlandi')}
function renderGroups(){const bar=$('groupBar');bar.innerHTML='';state.groups.forEach(g=>{const b=document.createElement('button');b.className='gbtn'+(g.id===state.activeGroupId?' active':'');b.textContent=g.name;b.onclick=()=>{state.activeGroupId=g.id;state.editorClosed=false;saveLocal();render()};bar.appendChild(b)});const add=document.createElement('button');add.className='btn outline';add.textContent='+ Guruh';add.onclick=openGroups;bar.appendChild(add)}
function renderSettings(){const g=group();$('reportTitle').value=state.reportTitle;$('workDate').value=state.date;$('quizTotal').value=g.quizTotal;$('ratingEnabled').checked=g.ratingEnabled}
function rowHtml(s){const absent=s.attendance==='kelmadi';const opt=(field,val,label,tone)=>`<button class="opt ${s[field]===val?'on '+tone:''}" data-act="${field}" data-val="${val}" ${absent&&field!=='attendance'?'disabled':''}>${label}</button>`;return `<div class="srow" data-id="${s.id}"><div><input type="checkbox"></div><div class="mobilelabel" data-label="Ism familiya"><input class="input nameinput" data-name value="${esc(s.name)}" title="${esc(s.name)}"></div><div class="mobilelabel" data-label="Davomat"><div class="status">${opt('attendance','keldi','Keldi','good')}${opt('attendance','kech','Kech qolib keldi','warn')}${opt('attendance','kelmadi','Kelmadi','bad')}</div></div><div class="mobilelabel" data-label="So‘zlar"><div class="status">${opt('vocab','topshirdi','Topshirdi','good')}${opt('vocab','chala','Chala topshirdi','warn')}${opt('vocab','topshirmadi','Topshirmadi','bad')}</div></div><div class="mobilelabel" data-label="Grammatika"><div class="status">${opt('grammar','topshirdi','Topshirdi','good')}${opt('grammar','chala','Chala topshirdi','warn')}${opt('grammar','topshirmadi','Topshirmadi','bad')}</div></div><div class="mobilelabel" data-label="Quiz"><div class="quizbox"><input class="input quizinput" data-quiz type="number" min="0" max="${group().quizTotal}" inputmode="numeric" value="${s.quiz??''}" ${absent?'disabled':''}><span class="sub">/${group().quizTotal}</span><span class="pct">${s.quiz!=null?Math.round(s.quiz/group().quizTotal*100)+'%':''}</span></div></div><div><button class="del" data-del>🗑</button></div></div>`}
function esc(v){return String(v??'').replace(/&/g,'&amp;').replace(/"/g,'&quot;').replace(/</g,'&lt;')}
function bindRow(el){const id=el.dataset.id;el.querySelector('[data-name]').addEventListener('input',e=>{const s=group().students.find(x=>x.id===id);s.name=e.target.value;e.target.title=e.target.value;group().roster=group().students.map(x=>x.name);saveLocal();updateReports()});el.querySelector('[data-quiz]').addEventListener('input',e=>{const s=group().students.find(x=>x.id===id);let v=e.target.value;s.quiz=v===''?null:Math.max(0,Math.min(group().quizTotal,Number(v)||0));el.querySelector('.pct').textContent=s.quiz==null?'':Math.round(s.quiz/group().quizTotal*100)+'%';saveLocal();updateReports()});el.querySelectorAll('[data-act]').forEach(b=>b.onclick=()=>{const s=group().students.find(x=>x.id===id),field=b.dataset.act,val=b.dataset.val;if(field==='attendance'){s.attendance=s.attendance===val?null:val;if(s.attendance==='kelmadi'){s.vocab=null;s.grammar=null;s.quiz=null}}else{s[field]=s[field]===val?null:val}saveLocal();renderStudentRow(id);updateReports()});el.querySelector('[data-del]').onclick=()=>confirmModal('O‘quvchini o‘chirish',`“${group().students.find(x=>x.id===id)?.name||'O‘quvchi'}” o‘chirilsinmi?`,()=>{group().students=group().students.filter(x=>x.id!==id);group().roster=group().students.map(x=>x.name);saveLocal();render()})}
function renderStudentRow(id){const old=document.querySelector(`.srow[data-id="${id}"]`);const s=group().students.find(x=>x.id===id);if(!old||!s)return;const tmp=document.createElement('div');tmp.innerHTML=rowHtml(s);const ne=tmp.firstElementChild;old.replaceWith(ne);bindRow(ne)}
function renderStudents(){const box=$('studentRows');box.innerHTML='';group().students.forEach(s=>{const tmp=document.createElement('div');tmp.innerHTML=rowHtml(s);const el=tmp.firstElementChild;box.appendChild(el);bindRow(el)});$('studentCount').textContent='Jami: '+group().students.length+' o‘quvchi'}
function taskLabel(v){return v==='topshirdi'?'✅ Topshirdi':v==='chala'?'⚠️ Chala topshirdi':v==='topshirmadi'?'❌ Topshirmadi':'➖ Belgilanmagan'}
function mainText(src){const h=[`📚 Bugun dars hisoboti`,`👥 Guruh: ${src.groupName}`,`📅 Sana: ${fmt(src.date)}`];const arr=src.students.filter(s=>s.name.trim()).map((s,i)=>{let l=[`${i+1}. ${s.name.trim()}`];if(s.attendance==='kelmadi'){l.push('🚫 Darsga kelmadi');return l.join('\n')}l.push(`👨‍🏫 Davomat: ${s.attendance==='keldi'?'✅ Keldi':s.attendance==='kech'?'⏰ Kech qolib keldi':'➖ Belgilanmagan'}`);l.push(`🔤 So‘zlar: ${taskLabel(s.vocab)}`);l.push(`📘 Grammatika: ${taskLabel(s.grammar)}`);l.push(`📝 Quiz / test: ${s.quiz==null?'➖':`${s.quiz}/${src.quizTotal} (${Math.round(s.quiz/src.quizTotal*100)}%)`}`);return l.join('\n')});return h.join('\n')+'\n\n'+(arr.join('\n\n')||'O‘quvchilar kiritilmagan.')}
function absText(src){const a=src.students.filter(s=>s.name.trim()&&s.attendance==='kelmadi');return [`🚫 Darsga kelmaganlar`,`👥 Guruh: ${src.groupName}`,`📅 Sana: ${fmt(src.date)}`,'',...(a.length?a.map((s,i)=>`${i+1}. ${s.name.trim()}`):['✅ Bugun barcha o‘quvchilar darsda qatnashdi.'])].join('\n')}
function score(s,g){if(s.attendance==='kelmadi')return 0;const t=v=>v==='topshirdi'?100:v==='chala'?50:0;const q=s.quiz==null?0:Math.min(100,s.quiz/g.quizTotal*100);return Math.round(t(s.vocab)*.25+t(s.grammar)*.25+q*.5)}
function ratingText(src){const ranked=src.students.filter(s=>s.name.trim()).map(s=>({s,p:score(s,group())})).sort((a,b)=>b.p-a.p);return [`🏆 Dars reytingi`,`👥 Guruh: ${src.groupName}`,`📅 Sana: ${fmt(src.date)}`,'',...ranked.map((r,i)=>`${['🥇','🥈','🥉'][i]||''}${i+1}. ${r.s.name.trim()} — ${r.p}%`)].join('\n')}
function source(){const g=group();return{title:state.reportTitle,groupName:g.name,date:state.date,quizTotal:g.quizTotal,students:g.students}}
function updateReports(){const s=source();$('mainReport').value=mainText(s);$('absenceReport').value=absText(s);$('ratingReport').value=ratingText(s);renderRating()}
function renderRating(){const g=group();$('ratingCard').classList.toggle('hidden',!g.ratingEnabled);if(!g.ratingEnabled)return;const ranked=g.students.filter(s=>s.name.trim()).map(s=>({s,p:score(s,g)})).sort((a,b)=>b.p-a.p);$('ratingList').innerHTML=ranked.map((r,i)=>`<div class="rank"><div>${['🥇','🥈','🥉'][i]||i+1}</div><b title="${esc(r.s.name)}">${esc(r.s.name)}</b><div class="score">${r.p}%</div></div>`).join('')||'<div class="sub">Ma’lumot yo‘q</div>'}
function renderArchives(){const list=$('archiveList'),ar=state.archives[group().id]||{},dates=Object.keys(ar).sort().reverse();if(!dates.length){list.innerHTML='Hozircha yo‘q';return}list.innerHTML=dates.slice(0,20).map(d=>`<button class="btn outline" style="width:100%;justify-content:space-between;margin:3px 0" data-ar="${d}"><span>${fmt(d)}</span><span>›</span></button>`).join('');list.querySelectorAll('[data-ar]').forEach(b=>b.onclick=()=>openArchive(b.dataset.ar))}
function openArchive(date){const a=selectedArchive(date);if(!a)return;showModal('Saqlangan hisobot',`<div class="sub" style="margin-bottom:8px">${fmt(date)} · ${esc(a.groupName||group().name)}</div><textarea id="archiveText" class="input" style="min-height:280px">${esc(mainText({groupName:a.groupName||group().name,date:a.date||date,quizTotal:a.quizTotal||50,students:a.students||[]}))}</textarea><div class="modalacts"><button id="copyAr" class="btn outline">📋 Nusxa</button><button id="editAr" class="btn soft">✏️ Tahrirlash</button><button id="delAr" class="btn danger">🗑 O‘chirish</button></div>`,null,false);setTimeout(()=>{$('copyAr').onclick=()=>copy($('archiveText').value);$('delAr').onclick=()=>confirmModal('Hisobotni o‘chirish',`${fmt(date)} hisoboti o‘chirilsinmi?`,()=>{delete state.archives[group().id][date];saveLocal();closeModal();render()});$('editAr').onclick=()=>{state.returnSession={groupId:group().id,date:state.date,students:deep(group().students),editorClosed:state.editorClosed};group().students=deep(a.students||[]);group().quizTotal=a.quizTotal||group().quizTotal;group().ratingEnabled=!!a.ratingEnabled;state.date=date;state.archiveEditing={groupId:group().id,date};state.editorClosed=false;closeModal();saveLocal();render()};},0)}
function saveClose(){const g=group();state.archives[g.id]=state.archives[g.id]||{};state.archives[g.id][state.date]={date:state.date,savedAt:new Date().toISOString(),students:deep(g.students),groupName:g.name,quizTotal:g.quizTotal,reportTitle:state.reportTitle,ratingEnabled:g.ratingEnabled};state.editorClosed=true;state.archiveEditing=null;saveLocal();render();toast('Hisobot saqlandi ✅')}
function newLesson(date=state.date){const g=group();g.roster=g.students.map(s=>s.name);g.students=freshStudents(g);state.date=date;state.editorClosed=false;state.archiveEditing=null;saveLocal();render()}
function renderClosed(){const closed=state.editorClosed;$('editorCard').classList.toggle('hidden',closed);$('reportsWrap').classList.toggle('hidden',closed);$('ratingCard').classList.toggle('hidden',closed||!group().ratingEnabled);$('closedCard').classList.toggle('hidden',!closed);$('closedText').textContent=`${fmt(state.date)} — ${group().name}`}
function render(){if(!state)return;renderGroups();renderCalendar();renderSettings();renderStudents();renderArchives();$('editorTitle').textContent=`👩‍🏫 ${group().name} — ${fmt(state.date)}`;renderClosed();updateReports()}
function showModal(title,html,onOk,showDefault=true){$('modalTitle').textContent=title;$('modalBody').innerHTML=html;$('modalBg').classList.remove('hidden');modalAction=onOk;$('modalOk').classList.toggle('hidden',!showDefault)}function closeModal(){$('modalBg').classList.add('hidden');modalAction=null}
function confirmModal(title,text,fn){showModal(title,`<p>${esc(text)}</p>`,fn,true);$('modalOk').textContent='Ha, davom etish';$('modalOk').className='btn danger'}
function openGroups(){const html=`<div id="groupsEdit">${state.groups.map(g=>`<div style="display:flex;gap:6px;margin:6px 0"><input class="input" data-gname="${g.id}" value="${esc(g.name)}"><button class="btn danger" data-gdel="${g.id}" ${state.groups.length===1?'disabled':''}>O‘chirish</button></div>`).join('')}</div><div style="display:flex;gap:6px;margin-top:10px"><input id="newGName" class="input" placeholder="Yangi guruh nomi"><button id="addG" class="btn primary">+ Qo‘shish</button></div>`;showModal('Guruhlar',html,()=>{document.querySelectorAll('[data-gname]').forEach(i=>{const g=state.groups.find(x=>x.id===i.dataset.gname);if(g)g.name=i.value.trim()||g.name});saveLocal();closeModal();render()});setTimeout(()=>{document.querySelectorAll('[data-gdel]').forEach(b=>b.onclick=()=>{const id=b.dataset.gdel;if(state.groups.length<=1)return;state.groups=state.groups.filter(g=>g.id!==id);delete state.archives[id];if(state.activeGroupId===id)state.activeGroupId=state.groups[0].id;saveLocal();openGroups()});$('addG').onclick=()=>{const n=$('newGName').value.trim();if(!n)return;const g={id:uid('gr'),name:n,roster:[],students:[],quizTotal:50,ratingEnabled:false};state.groups.push(g);state.activeGroupId=g.id;saveLocal();openGroups()};},0)}
async function copy(t){try{await navigator.clipboard.writeText(t);toast('Nusxa olindi ✅')}catch{const ta=document.createElement('textarea');ta.value=t;document.body.appendChild(ta);ta.select();document.execCommand('copy');ta.remove();toast('Nusxa olindi ✅')}}